### ISSUE TITLE
1.8 Checklist

### ISSUE THREAD

**Issue by TheCricket** [Chisel-2/Chisel-2#353]
-----------------
Code TODO:
-----------------

- [ ] Do the "other" classes
- [ ] Do the wood classes

======================================
JSON's for the following blocks need to be done
======================================
- [ ] Acacia
- [ ] Aluminum
- [ ] Andesite
- [ ] Antiblock
- [ ] Birch
- [ ] Bookshelf
- [ ] Bricks
- [ ] Bronze
- [ ] Carpet
- [ ] Carpet Floor
- [ ] Chest
- [ ] Cobblestone
- [ ] Concrete
- [ ] Copper
- [ ] Dark Oak
- [ ] Diamond
- [ ] Diorite
- [ ] Dirt
- [ ] Emerald
- [ ] Energised Voidstone
- [ ] Energised Voidstone Pillar
- [ ] Factory
- [ ] Fantasy
- [ ] Futura
- [ ] Glass
- [ ] Glass Pane
- [ ] Glowstone
- [ ] Gold
- [ ] Granite
- [ ] Grimstone
- [ ] Hex Plating
- [ ] Holystone
- [ ] Ice
- [ ] Ice Pillar
- [ ] Imperial
- [ ] Iron
- [ ] Iron Bars
- [ ] Jungle
- [ ] Laboratory
- [ ] Lapis
- [ ] Large Hex Plating
- [ ] Lavastone
- [ ] Lead
- [ ] Leaves
- [ ] Mossy Cobblestone
- [ ] Mossy Temple
- [ ] Nether Brick
- [ ] Netherrack
- [ ] Oak
- [ ] Obsidian
- [ ] Packed Ice
- [ ] Packed Ice Pillar
- [ ] Purple Fantasy
- [ ] Rebel
- [ ] Redstone
- [ ] Road Line
- [ ] Runic Voidstone
- [ ] Sandstone
- [ ] Sandstone Scribbles
- [ ] Silver
- [ ] Snakestone Sand
- [ ] Snakestone Stone
- [ ] Spruce
- [ ] Stained Glass Black
- [ ] Stained Glass Red
- [ ] Stained Glass Green
- [ ] Stained Glass Brown
- [ ] Stained Glass Blue
- [ ] Stained Glass Purple
- [ ] Stained Glass Cyan
- [ ] Stained Glass Light Gray
- [ ] Stained Glass Gray
- [ ] Stained Glass Pink
- [ ] Stained Glass Lime
- [ ] Stained Glass Yellow
- [ ] Stained Glass Light Blue
- [ ] Stained Glass Magenta
- [ ] Stained Glass Orange
- [ ] Stained Glass White
- [ ] Stained Glass Pane Black
- [ ] Stained Glass Pane Red
- [ ] Stained Glass Pane Green
- [ ] Stained Glass Pane Brown
- [ ] Stained Glass Pane Blue
- [ ] Stained Glass Pane Purple
- [ ] Stained Glass Pane Cyan
- [ ] Stained Glass Pane Light Gray
- [ ] Stained Glass Pane Gray
- [ ] Stained Glass Pane Pink
- [ ] Stained Glass Pane Lime
- [ ] Stained Glass Pane Yellow
- [ ] Stained Glass Pane Light Blue
- [ ] Stained Glass Pane Magenta
- [ ] Stained Glass Pane Orange
- [ ] Stained Glass Pane White
- [ ] Steel
- [ ] Stone Bricks
- [ ] Technical
- [ ] Temple
- [ ] Tin
- [ ] Torch
- [ ] Transparent Technical
- [ ] Tyrian
- [ ] Uranium
- [ ] Valentines
- [ ] Voidstone
- [ ] Warning
- [ ] Waterstone
- [ ] Woolen Clay

========================================================
If you would like to submit JSON's please follow the variant names in com.cricketcraft.block.variant.BlockVariants
========================================================

**Comment by Drullkus** [comment]
Nope nope I'm not doing this D:

**Comment by TheCricket** [comment]
lol
